version: '2'
services:
  web:
    build: ./
    volumes:
      - ./:/var/www/app
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - PORT=8080
    command: sh -c 'node /var/www/app/app.js'